version: '3.7'

services:
  api:
      build:
        context: ./backend
        dockerfile: Dockerfile
      depends_on:
        - mongo
      restart: on-failure
      ports:
        - "8000:80/tcp"
  mongo:
    image: mongo
    restart: always
